name: intl_phone_number_input
description: A simple and customizable flutter package for inputting phone number in intl / international format uses Google's libphonenumber.
version: 0.7.4
homepage: https://github.com/natintosh/intl-phone-number-input

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dlibphonenumber: ^1.1.17
  equatable: ^2.0.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flags/
